config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # Local
    path('', include('fake_news_detection.urls', namespace="fake_news_detection")),
]

fake_news_detection/urls.py
from django.urls import path, include
from fake_news_detection import views

app_name = "fake_news_detection"

urlpatterns = [
    path('', views.index, name="home"),
    path('result/', views.result, name="result"),
    path('satisfaction/', views.satisfaction, name="satisfaction"),
    path('a/', views.a, name="a"),
]

fake_news_detection/models.py
from django.db import models

# Create your models here.
class NewsArticle(models.Model):
    CATEGORY_CHOICES = (
        ("Business", "Business"),
        ("Cars", "Cars"),
        ("Entertainment", "Entertainment"),
        ("Family", "Family"),
        ("Health", "Health"),
        ("Politics", "Politics"),
        ("Religion", "Religion"),
        ("Science", "Science"),
        ("Sports", "Sports"),
        ("Technology", "Technology"),
        ("Travel", "Travel"),
        ("Video", "Video"),
        ("World", "World")
    )

    newspaper = models.CharField(max_length=100)
    category = models.CharField(max_length=100, choices=CATEGORY_CHOICES, default="Politics")
    news_text = models.CharField(max_length=5000)
    label = models.CharField(max_length=10, default="Fake")

    def __str__(self):
        return self.news_text

fake_news_detection/forms.py
from django import forms
from fake_news_detection.models import NewsArticle


class NewsArticleForm(forms.ModelForm):
    
    class Meta:
        model = NewsArticle
        # fields = '__all__'
        fields = ('newspaper', 'category', 'news_text', )
        labels = {
            'newspaper': 'Write down the name of the newspaper (Example: CNN):',
            'category': 'Select the category of the news article',
            'news_text': "Write down the text you want to predict whether it's fake or not."
        }
        widgets = {
            'news_text': forms.Textarea(
            )
        }

    def __init__(self, *args, **kwargs):
        super(NewsArticleForm, self).__init__(*args, **kwargs)
        self.fields['category'].empty_label = "Select a category..."

fake_news_detection/views.py
import joblib

from django.shortcuts import render
from django.http import JsonResponse
from django.http import HttpResponse

from sklearn.feature_extraction.text import TfidfVectorizer

from fake_news_detection.models import NewsArticle
from fake_news_detection.forms import NewsArticleForm


tfidf_vectorizer = joblib.load('vectorizer.sav')
pac = joblib.load('model.sav')

def base(request):
	return render(request, 'base.html')


def index(request):
	if request.method == 'GET':
		form = NewsArticleForm()
		return render(request, 'fake_news_detection/index.html', {'form': form})

def a(request):
	form = NewsArticleForm()
	if request.is_ajax and request.method == "POST":
		newspaper = request.POST.get("newspaper")
		category = request.POST.get("category")
		news_text = request.POST.get("news_text")
		vec_news_text = tfidf_vectorizer.transform([news_text])
		ans = pac.predict(vec_news_text)
		print(ans)

		return JsonResponse({"prediction": ans[0]}, status=200)


	return render(request, 'fake_news_detection/a.html', {'form': form})


def result(request):
	form_params = request.GET
	news_text = form_params['news_text']

	vec_news_text = tfidf_vectorizer.transform([news_text])
	ans = pac.predict(vec_news_text)

	context = {
		'ans': ans[0], 
		'form_params': form_params
	}

	request.session['results'] = context

	return render(request, "fake_news_detection/result.html", context)


def satisfaction(request):
	results = request.session.get('results')
	print(f"[D] We're on satisfaction page => {results}")
	print(f"[***] NEWSPAPER => {results['form_params']['newspaper']}")
	print(f"[***] CATEGORY => {results['form_params']['category']}")
	print(f"[***] NEWSTEXT => {results['form_params']['news_text']}")
	print(f"[***] LABEL => {results['ans']}")

	args_sent_by_user = request.GET

	if "user_choice" in args_sent_by_user:
		print("[+] USER IS SATISFIED. SAVE THE MODEL TO THE DATABASE.")

		newspaper = results['form_params']['newspaper']
		category = results['form_params']['category']
		news_text = results['form_params']['news_text']
		label = results['ans']

		form = NewsArticleForm(results['form_params'])
		if form.is_valid():
			NewsArticle.objects.create(newspaper=newspaper, category=category, news_text=news_text, label=label)

	return render(request, "fake_news_detection/satisfaction.html", {'args_sent_by_user': args_sent_by_user})

fake_news_detection/templates/base.html
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <title>Fake News Detection</title>
    </head>

    <body style="background-color: #c94c4c;">
        <nav>
            <div class="container nav-wrapper">
                <a href="/" class="brand-logo">Fake News Detection</a>
                <ul id="nav-mobile" class="right">
                    <li><a href="/">Home</a></li>
                </ul>
            </div>
        </nav>

        <div class="container">
            <h1 style="text-align: center;">The fake news detector you didn't know you needed.</h1>
            
            <div class="row">
                <div class="col s4"> <!--s4 is the size of the column-->
                    <!-- Promo content 1 goes here -->
                    <div class="center">
                        <i class="large material-icons" style="color: #ee6e73">sick</i>
                        <p>Is the dis(information) age making you sick?</p>
                        <p class="light center">Don't fret, and cure your illness with this brand-new detector.</p>
                    </div>
                </div>

                <div class="col s4">
                    <!--Promo content 2 goes here-->
                    <div class="center">
                        <i class="large material-icons" style="color: green">fact_check</i>
                        <p>Fact-check the news you read every day.</p>
                        <p class="light center">Just copy the text you want to try out, and paste it below.</p>
                    </div>
                </div>

                <div class="col s4">
                    <!--Promo content 3 goes here-->
                    <div class="center">
                        <i class="large material-icons" style="color: #fa9905">sentiment_very_satisfied</i>
                        <p>A Machine Learning approach.</p>
                        <p class="light center">The more you use the platform, the better it becomes.</p>
                    </div>
                </div>
            </div>

            <form action="" method="POST">
                {% csrf_token %}
                <input type="text" name="search" placeholder="Paste the news text you want to fact-check here.">
                <button class="btn waves-effect waves-light" type="submit" name="action">FACT-CHECK
                    <i class="material-icons right">mood</i>
                </button>
            </form>
            
            <!--Inheritance of the full code-->
            {% block content %}
            {% endblock content %}
            <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        </div>

    </body>
</html>

fake_news_detection/templates/fake_news_detection/a.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Fake News Detection</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <!-- <link href="{% static 'fake_news_detection/img/favicon.png' %}" rel="icon"> -->
  <!-- <link href="{% static 'fake_news_detection/img/apple-touch-icon.png' %}" rel="apple-touch-icon"> -->

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'fake_news_detection/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'fake_news_detection/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'fake_news_detection/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'fake_news_detection/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'fake_news_detection/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'fake_news_detection/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <!-- Template Main CSS File -->
  <link href="{% static 'fake_news_detection/css/style.css' %}" rel="stylesheet">

</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top  header-transparent ">
    <div class="container d-flex align-items-center justify-content-between">

      <div class="logo">
        <h1><a href="{% url 'fake_news_detection:home' %}">Fake News Detection</a></h1>
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
          <li><a class="nav-link scrollto" href="#contact">Fake news detector</a></li>
          <li><a class="getstarted scrollto" href=""><i class="bi bi-github"></i> &nbsp;&nbsp; Github</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">

    <div class="container">

        <div class="row content">
          <div class="col-md-4" data-aos="fade-right">
            <img src="{% static 'fake_news_detection/img/details-1.png' %}" class="img-fluid" alt="">
          </div>
          <div class="col-md-8 pt-4" data-aos="fade-up">
            <h3>The fake news detector you didn't know you needed.</h3>
            <p class="fst-italic">
              Fake news has become a critical issue that is affecting the world and it has led to loss of lives, reputation and much more. You need a reliable fake news detector that can detect fake news right in the moment it is published or beginning of distribution.
            </p>
            <ul>
              <li><i class="bi bi-check"></i> A Machine Learning based approach.</li>
              <li><i class="bi bi-check"></i> Training dataset with over 20,000 news articles.</li>
              <li><i class="bi bi-check"></i> De-clutter your mind from fake negative news.</li>
            </ul>
            <p>
              Journalists that don't know how to detect fake news on social media sites like Facebook and Twitter, risk losing their audience and credibility. Help them fight fake news with the Fake News Detection Tool!
            </p>
          </div>
        </div>

      </div>

  </section><!-- End Hero -->

  <main id="main">

    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Fake news detector</h2>
          <p>Fill in the details below to predict if an article contains Fake News</p>
        </div>

        <div class="row">

          <div class="col-lg-6">
            <form action="" method="" role="form" class="php-email-form" data-aos="fade-up">
              {% csrf_token %}
              <div class="form-group">
                <input placeholder="Name of the newspaper. (Ex. cnn, etc)" type="text" name="newspaper" class="form-control" id="newspaper" required>
              </div>

              <div class="form-group mt-3">
                <select class="form-select" name="category" aria-label="Default select example">
                  <option value="Business" selected>Business</option>
                  <option value="Cars">Cars</option>
                  <option value="Entertainment">Entertainment</option>
                  <option value="Family">Family</option>
                  <option value="Health">Health</option>
                  <option value="Politics">Politics</option>
                  <option value="Religion">Religion</option>
                  <option value="Science">Science</option>
                  <option value="Sports">Sports</option>
                  <option value="Technology">Technology</option>
                  <option value="Travel">Travel</option>
                  <option value="Video">Video</option>
                  <option value="World">World</option>
                </select>
              </div>
              <div class="form-group mt-3">
                <textarea placeholder="News article text" class="form-control" name="news_text" rows="5" required></textarea>
              </div>
              <div class="text-center submit-btn"><button type="submit">Fact Check</button></div>
            </form>
          </div>

          <div class="col-lg-6">
            <div class="row">
              <div class="col-lg-12 info result">
                <div id="initial_text">
                  <strong>Submit the article to predict results</strong>
                </div>
                <div id="submit_feedback" class="hide">
                  <h1 id="ans"></h1>
                  <div>
                    <p>Satisfied with the result?</p>
                    <div>
                      <i id="up" class="pointer bx bx-like"></i> <i id="down" class="pointer bx bx-dislike"></i>
                    </div>
                  </div>
                </div>
                <div id="feedback" class="hide">
                  <strong>Thanks for the feedback!</strong>
                </div>
              </div>
            </div>
          </div>

        </div>

      </div>
    </section><!-- End Contact Section -->

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="container py-4">
      <div class="copyright">
        &copy; <strong><span>Fake News Detector</span></strong>.
      </div>
      <div class="credits">
        Designed by <strong>&lt;Your name&gt;</strong>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'fake_news_detection/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'fake_news_detection/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'fake_news_detection/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'fake_news_detection/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>


  <!-- Template Main JS File -->
  <script src="{% static 'fake_news_detection/js/main.js' %}"></script>

  <script>
  $(".php-email-form").submit(function (e) {
    e.preventDefault();
    var serializedData = $(this).serialize();
    console.log(serializedData);

    $.ajax({
        type: 'POST',
        url: "{% url 'fake_news_detection:a' %}",
        data: serializedData,
        success: function (response) {
            console.log(response);
            $("#submit_feedback").removeClass("hide");
            $("#initial_text").hide();
            $("#ans").html(response['prediction']);
        },
        error: function (response) {
            // alert the error if any error occured
            console.log(response);
        },
    })
  });

  $("#up").click(function (e) {
    e.preventDefault();
    console.log(e);
    $("#feedback").removeClass("hide");
  });
  </script>

</body>

</html>

fake_news_detection/templates/fake_news_detection/base.html
{% load static %}


<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="{% static 'fake_news_detection/styles.css' %}">
        <title>Fake News Detection</title>
    </head>

    <body>
        <nav>
            <div class="container nav-wrapper">
                <a href="/" class="brand-logo">Fake News Detection</a>
                <ul id="nav-mobile" class="right">
                    <li><a href="/">Home</a></li>
                </ul>
            </div>
        </nav>

        <div class="container">
            <h1 style="text-align: center;">The fake news detector you didn't know you needed.</h1>
            
            <div class="row">
                <div class="col s4"> <!--s4 is the size of the column-->
                    <!-- Promo content 1 goes here -->
                    <div class="center">
                        <i class="large material-icons" style="color: #ee6e73">sick</i>
                        <p>Is the dis(information) age making you sick?</p>
                        <p class="light center">Don't fret, and cure your illness with this brand-new detector.</p>
                    </div>
                </div>

                <div class="col s4">
                    <!--Promo content 2 goes here-->
                    <div class="center">
                        <i class="large material-icons" style="color: green">fact_check</i>
                        <p>Fact-check the news you read every day.</p>
                        <p class="light center">Just copy the text you want to try out, and paste it below.</p>
                    </div>
                </div>

                <div class="col s4">
                    <!--Promo content 3 goes here-->
                    <div class="center">
                        <i class="large material-icons" style="color: #fa9905">sentiment_very_satisfied</i>
                        <p>A Machine Learning approach.</p>
                        <p class="light center">If you're satisfied, we collect the results of the news you send to us.</p>
                    </div>
                </div>
            </div>

            {%  block form %}
            {% endblock form %}
            
            <!--Inheritance of the full code-->
            {% block content %}
            {% endblock content %}
            <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        </div>

    </body>
</html>

fake_news_detection/templates/fake_news_detection/index.html
{% extends 'fake_news_detection/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block form %}
    <form method="" action="{% url 'fake_news_detection:result' %}" autocomplete="off" style="{% static 'styles.css' %}">
        {% csrf_token %}

        {{ form.newspaper|as_crispy_field }}
        <br>

        {{ form.category|as_crispy_field }}
        <br>

        {{ form.news_text|as_crispy_field }}
        <br>

        <button class="btn waves-effect waves-light btn" style="width: 100%;" type="submit" name="action">FACT-CHECK
            <i class="material-icons right">mood</i>
        </button>
    </form>

{% endblock form %}

fake_news_detection/templates/fake_news_detection/result.html
{% extends 'fake_news_detection/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block form %}
{% endblock form %}

{% block content %}

  <center>
  <h2>We believe that news article from {{form_params.newspaper}} could be potentially</h2>
  
  {% if ans == 'Real' %}
    <strong style="font-size: 10rem; color: green;">{{ans}}</strong>

  {% else %}
    <strong style="font-size: 10rem; color: red;">{{ans}}</strong>
  
  {% endif %}
  
  </center>
  
  <p>Check the next checkbox if you're happy with your results.</p>

  <form action="{% url 'satisfaction' %}">
    {% csrf_token %}

    <p>
      <label>
        <input type="checkbox" name="user_choice" />
        <span>I think the prediction was accurate.</span>
      </label>
    </p>

    <button class="btn waves-effect waves-light btn" style="width: 100%;" type="submit" name="submit_button">SUBMIT FEEDBACK
        <i class="material-icons right">send</i>
    </button>
  </form>
{% endblock content %}

fake_news_detection/templates/fake_news_detection/satisfaction.html
{% extends 'fake_news_detection/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block form %}
{% endblock form %}

{% block content %}

  <center>
    <h2>Thank you!</h2>
  
  {% if "user_choice" in args_sent_by_user %}
    <p>We'll store and process your results for better predictions.</p>

  {% else %}
    <p>We won't save any data of yours.</p>
  {% endif %}

  <a class="waves-effect waves-light btn-large" href="{% url 'home' %}"><i class="material-icons left">science</i>Try again</a>

  </center>

  <br>
  
{% endblock content %}

{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Fake News Detection</h1>

  {% if "user_choice" in args_sent_by_user %}
    <p>Thank you. We'll store and process your results for better predictions.</p>

  {% else %}
    <p>Thank you. Come back soon.</p>
  {% endif %}
</body>
</html> {% endcomment %}